### ISSUE TITLE
laurel_sprout links are dead

### ISSUE THREAD

**Issue by nuJIbMeHb** [XiaomiFirmwareUpdater/miui-updates-tracker#122]
could not download any updates nor fastboot either recovery for laurel_sprout (mi a3). all the links shows me the following
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>62FC8913A846BB36338DB255</RequestId>
<HostId>bigota.d.miui.com</HostId>
<Key>V12.0.26.0.RFQMIXM/laurel_sprout_global_images_V12.0.26.0.RFQMIXM_20220808.0000.00_11.0_2292e2c0b1.tgz</Key>
</Error>
```
is this xiomiside error? 'cause other links for other devices are fine and working

**Comment by yshalsager** [comment]
@nuJIbMeHb Yes, once again the links were removed by them and I can do nothing :(
