### ISSUE TITLE
[Bug]Chinese fastboot files tracker might broked somehow

### ISSUE THREAD

**Issue by HegeKen** [XiaomiFirmwareUpdater/miui-updates-tracker#203]
It's crawling recovery files with timestamps in the urls within recent 2 pushes.

as:
miui_DAUMIER_V14.0.8.0.TLGCNXM_a3aff9f955_13.0.zip?t=1691139776&s=1a13f7c772d2860f94f325bee8c0c37c

**Comment by yshalsager** [comment]
@HegeKen Huge thanks for reporting, I have resolved the problem.
