### ISSUE TITLE
strip timestamps and s_keys from fastboot links

### ISSUE THREAD

**Issue by HegeKen** [XiaomiFirmwareUpdater/miui-updates-tracker#225]
I noticed that Xiaomi Community download page added timestamps and s_keys after casual links, it's used to limit download speed, if those two are not a pair, download speeds are limited to 100k/s here in mainland China , and also domain names are changed to ultimateota and superota for those specific roms, I don't know when these changes takes place in global regions.
You can download roms without timestamp and s_keys using bigota and hugeota ,but not in other two, and problem is how togenerate s_key.

example:
https://bigota.d.miui.com/V14.0.8.0.TKHMIXM/alioth_global_images_V14.0.8.0.TKHMIXM_20230904.0000.00_13.0_global_8d24b98f2a.tgz?&s=73b6e37926a356df010376a7fe0b1e1a

**Comment by yshalsager** [comment]
Thanks! fixed in [3512c64](https://github.com/XiaomiFirmwareUpdater/miui-updates-tracker/commit/3512c64ef05b371bfc308a672090c59b17c3e28f)
