### ISSUE TITLE
Some roms is missing

### ISSUE THREAD

**Issue by kejiweixun** [XiaomiFirmwareUpdater/miui-updates-tracker#245]
Hi, miui update checker seems to miss some updates.

For example, xiaomi 13(fuxi)'s beta updates is missing:
- OS1.0.23.12.2.DEV
- OS1.0.23.12.4.DEV
- OS1.0.23.12.11.DEV

xiaomi 13(fuxi)'s stable update is missing:
- OS1.0.3.0.UMCCNXM

Is it on purpose or is it a bug?

Thanks for your great work!

**Comment by yshalsager** [comment]
Hello, I have added all these missing ROMs. Thanks for reporting.

**Comment by kejiweixun** [comment]
Thanks! Where can i find these roms? The [xml file](https://github.com/XiaomiFirmwareUpdater/miui-updates-tracker/blob/master/rss/fuxi.xml) seems still mising some roms, for example OS1.0.23.12.2.DEV. The website is also missing.

<img width="1235" alt="截屏2023-12-20 08 29 36" src="https://github.com/XiaomiFirmwareUpdater/miui-updates-tracker/assets/6022398/12aa2af6-e93f-492b-8741-6d86174581d7">

**Comment by yshalsager** [comment]
> Thanks! Where can i find these roms? 

I have fixed an issue of hyperos pages not being shown for few devices, you can see them on the website now.

https://xiaomifirmwareupdater.com/archive/hyperos/fuxi/
