### ISSUE TITLE
Discus: Has Xiaomi terminated fastboot links api?

### ISSUE THREAD

**Issue by HegeKen** [XiaomiFirmwareUpdater/miui-updates-tracker#351]
Apparently using links like
https://update.miui.com/updates/miota-fullrom.php?d=corot_global&b=F&r=global&n=

will not give back fastboot files anymore.

**Comment by yshalsager** [comment]
Yeah, we noticed a few days ago, unfortunately didn't discover anything yet.

**Comment by HegeKen** [comment]
that's realy a bummer, thanks for your reply.

**Comment by kacskrz** [comment]
Change update.miui.com to update.intl.miui.com. It works.

**Comment by HegeKen** [comment]
> Change update.miui.com to update.intl.miui.com. It works.

Thanks for the great news!!!
