### ISSUE TITLE
no module named miui_tracker_official

### ISSUE THREAD

**Issue by Gray88811** [XiaomiFirmwareUpdater/miui-updates-tracker#86]
![image](https://user-images.githubusercontent.com/72987745/152319600-8ddf36bb-eb2e-4190-8d5c-9b8c763b960c.png)
As title says, script gives an error about module "miui_tracker_official"

**Comment by Gray88811** [comment]
Also, there is no CONF_DIR

**Comment by yshalsager** [comment]
You should run it as a module, the way you're doing currently is wrong.
